name: Publish PSMake
description: Builds PSMake

inputs:
  nuget-api-key:
    required: true
    type: string
  build-target:
    required: true
    default: Release
    type: string

runs:
  using: composite
  steps:

    - name: Build PSMake
      shell: pwsh
      run: |
        Import-Module ./PSMake.psd1
        PSMake publish ${{inputs.nuget-api-key}} ${{inputs.build-target}}