name: CI Tests
on:
    pull_request:

jobs:
    deploy:
        runs-on: ubuntu-latest
        container: mcr.microsoft.com/powershell
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - name: Install dependencies
              shell: pwsh
              run: |
                Install-Module Configuration -Force
                Install-Module PSScriptAnalyzer -Force

            - name: Run Tests
              shell: pwsh
              run: |
                Import-Module ./PSMake.psd1 -ErrorAction Stop
                psmake test reports

            - name: JUnit Report Action
              uses: mikepenz/action-junit-report@v4
              if: success() || failure()
              with:
                report_paths: ./PesterTestsReport.xml

            - name: JaCoCo Report
              uses: Madrapps/jacoco-report@v1.6.1
              if: success() || failure()
              with:
                token: ${{github.token}}
                paths: ${{github.workspace}}/CodeCoverageReport.xml
             

            
        
