name: CI
on:
    push:
        branches: ["main", "github-transition"]

jobs:
    deploy:
        runs-on: ubuntu-latest
        container: mcr.microsoft.com/powershell
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Get current directory
              shell: pwsh
              run: Get-ChildItem
            - name: Output environment
              shell: pwsh
              run: Get-ChildItem Env:\
            - name: Change to working directory
              shell: pwsh
              run: cd $env:WORKSPACE; Get-ChildItem
            - name: Install dependencies
              shell: pwsh
              run: Install-Module Configuration -Force
            - name: Run Tests
              shell: pwsh
              run: |
                Import-Module ./PSMake.psd1 -ErrorAction Stop
                psmake test

            
        
