on:
  push:
    branches:
      - main

jobs:
  publish-prerelease:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/powershell
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run Tests
        uses: ./.github/actions/unit-test

      - name: Test Reports
        uses: ./.github/actions/unit-test-reports

      - name: Build Project (Prerelease)
        uses: ./.github/actions/build
        with:
          build-target: Prerelease

      - name: Publish Project (Prerelease)
        uses: ./.github/actions/publish
        with:
          build-target: Prerelease
          nuget-api-key: ${{secrets.PSGALLERY_API_KEY}}