on:
  release:
    types: [prereleased, released]

jobs:
  release:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/powershell
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    
    - name: Install curl
      run: apt update && apt install -y curl

    - name: Install DotNet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Install dependencies
      uses: ./.github/actions/install-dependencies

    - name: Run Tests
      uses: ./.github/actions/unit-test

    - name: Test Reports
      uses: ./.github/actions/unit-test-reports

    - name: Set Release Information
      uses: ./github/actions/set-release
      with:
        tag-name: ${{ github.event.release.tag_name }}
        prerelease: ${{ github.event.release.prerelease }}
        body: ${{ github.event.release.body }}

    - name: Build Project (Release)
      uses: ./.github/actions/build
      with:
        build-target: Release

    - name: Publish Project (Release)
      uses: ./.github/actions/publish
      with:
        build-target: Release
        nuget-api-key: ${{secrets.PSGALLERY_API_KEY}}