on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  test-main-or-pr:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/powershell
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install curl
        run: apt update && apt install -y curl
    
      - name: Install DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run Tests
        uses: ./.github/actions/unit-test

      - name: Test Reports
        uses: ./.github/actions/unit-test-reports