name: Unit Test Reports
on:
    workflow_call:

jobs:
    test:
        runs-on: ubuntu-latest
        container: mcr.microsoft.com/powershell
        steps:
            - name: JUnit Report Action
              uses: mikepenz/action-junit-report@v4
              if: success() || failure()
              with:
                report_paths: ./PesterTestsReport.xml

            - name: JaCoCo Report
              uses: Madrapps/jacoco-report@v1.6.1
              if: success() || failure()
              with:
                token: ${{github.token}}
                paths: ${{github.workspace}}/CodeCoverageReport.xml
             

            
        
