on:
    workflow_call:

name: Unit Tests

jobs:
    test:
        runs-on: ubuntu-latest
        container: mcr.microsoft.com/powershell
        steps:
            - name: Run Tests
              shell: pwsh
              run: |
                Import-Module ./PSMake.psd1 -ErrorAction Stop
                psmake test reports